baseURL = "https://deployedthoughts.dev"
languageCode = "en-us"
title = "Stephen Shary"

[params]
  theme = "ink"
  themeMode = "auto"

[module]
  [[module.imports]]
    path = "github.com/ananthb/jughead"
